version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node

  publisaiz_java:
    container_name: publisaiz.java
    image: azul/zulu-openjdk-alpine:11
    volumes:
      - "../target:/home/app"
    ports:
      - "8080:80"
      - "8000:8000"
    command: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -jar /home/app/elastic-0.0.1-SNAPSHOT.jar
    restart: always

